apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
spec:
   revisionHistoryLimit: 10
   replicas: 2
   selector:
     matchLabels:
        app: javawebapp
   strategy:
     type: RollingUpdate
     rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
   minReadySeconds: 30
   template:
      metadata:
        name: java-web-pod
        labels:
           app: javawebapp
      spec:
        containers:
        - name: javawebcontainer
          image: uday745/javawebapp:5.0
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
             httpGet:
               path: /java-web-app
               port: 8080
             initialDelaySeconds: 30
             timeoutSeconds: 5
             periodSeconds: 15
          livenessProbe:
             httpGet:
               path: /java-web-app
               port: 8080
             initialDelaySeconds: 30
             timeoutSeconds: 5
             periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: javawebsvc
spec:
  type: NodePort
  selector:
     app: javawebapp
  ports:
  - port: 8089
    targetPort: 8080
    nodePort: 30456
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: javapodscaler
spec:
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: javawebapp
   minReplicas: 2
   maxReplicas: 5
   metrics:
   - type: Resource
     resource:
         name: cpu
         target:
            type: Utilization
            averageUtilization: 50

